### ISSUE TITLE
Релиз?

### ISSUE THREAD

**Issue by ilayshp** [abushinov/MaxToA#1]
Привет 

когда будет первый публичный тест бриджа?

**Comment by abushinov** [comment]
привет, конкретной даты нет, работаю над плагином по выходным, так что как будет готово, тогда и запущу публичный тест.

**Comment by ilayshp** [comment]
Владимир, спасибо ответ. Ты как из максон(с4д) - как будет так сразу(я про их секретность постановки сроков). 

Можно закрыть эту проблему(если хочешь можно прокомментировать, ты хозяин гита)
